### ISSUE TITLE
RuntimeError: error in LoadLibraryA

### ISSUE THREAD

**Issue by KHarsh98** [nii-yamagishilab/Capsule-Forensics-v2#4]
0%|          | 0/60 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  **File "D:/Capsule-Forensics-v2-master/test_binary_ffpp.py", line 88, in <module>
    classes, class_ = capnet(x, random=opt.random)**
  File "C:\Users\vatsa\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Capsule-Forensics-v2-master\model_big.py", line 181, in forward
    z = self.fea_ext(x)
  File "C:\Users\vatsa\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Capsule-Forensics-v2-master\model_big.py", line 84, in forward
    outputs = [capsule(x.detach()) for capsule in self.capsules]
  File "D:\Capsule-Forensics-v2-master\model_big.py", line 84, in <listcomp>
    outputs = [capsule(x.detach()) for capsule in self.capsules]
  File "C:\Users\vatsa\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\vatsa\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\vatsa\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Capsule-Forensics-v2-master\model_big.py", line 30, in forward
    return torch.stack((mean, std), dim=1)
RuntimeError: error in LoadLibraryA

In order to test the model, I downloaded a dataset from kaggle. However testing it presents this very issue. I tried searching the internet for solutions. However, I couldn't find any.
Any clues?

**Comment by honghuy127** [comment]
I think the problem is from some DLL files in MS Windows OS. It is better to use Linux-based OS to run the code.
